/** 
 * SECTION 10
 * JavaScript FUNCTION TYPE
 * FUNCTIONS ARE OBJECTS, FUNCTION NAMES ARE JUST POINTERS
 * EACH FUNCTION IS AN INSTANCE OF A FUNCTION TYPE
 * FUNCTION NAME WITHOUT () ACCESS THE FUNCTION BUT DOES NOT EXECUTE FUNCTION
 */
