// JavaScript OPERATORS 
/**
 * UNARY OPERATORS
 * BOOLEAN OPERATORS
 * MULTIPLICATIVE OPERATORS
 * ADDITIVE OPERATORS
 * RELATIONAL OPERATORS
 * EQUALITY OPERATORS
 * CONDITIONAL OPERATORS
 * ASSIGNMENT OPERATORS
 * COMMA OPERATORS
 */ 

 // UNARY OPERATORS is operator THAT WORKS ONLY ON ONE VALUE
var age = 50;
age++; // POSTFIX WAY
console.log(age);

var age2 = 50;
--age2; // PREFIX 
console.log(age2);

// CONVERSION 
